"""Create, update, refresh, and recover projects generated by Nix."""

import argparse
from contextlib import contextmanager
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import tomllib

from dependencies import plan_metadata
from transaction import (ConflictError, FileEdit, MANIFEST, apply_resolved_update, checked_path,
                         canonical_mode, load_manifest, matches, prepare_resolved_update, read_json,
                         read_state, recover, resolve_root)


class CommandError(ValueError):
    pass


def run(arguments, *, cwd=None):
    result = subprocess.run(list(map(str, arguments)), cwd=cwd, capture_output=True, text=True)
    if result.returncode:
        raise CommandError(f'{arguments[0]} failed:\n{result.stderr.strip()}')
    return result.stdout


def nix_value(value):
    """Serialize explicit CLI values without evaluating them as Nix source."""
    if isinstance(value, str):
        if any(ord(char) < 32 and char not in '\n\r\t' for char in value):
            raise ValueError('configuration strings contain unsupported control characters')
        return json.dumps(value, ensure_ascii=False).replace('${', '\\${')
    if value is None:
        return 'null'
    if type(value) is bool:
        return 'true' if value else 'false'
    if type(value) is int:
        return str(value)
    if type(value) is float:
        return '(builtins.fromJSON ' + nix_value(json.dumps(value, allow_nan=False)) + ')'
    if isinstance(value, list):
        return '[ ' + ' '.join(nix_value(item) for item in value) + ' ]'
    if isinstance(value, dict):
        return '{ ' + ' '.join(f'{nix_value(key)} = {nix_value(item)};' for key, item in value.items()) + ' }'
    raise ValueError(f'unsupported configuration value: {type(value).__name__}')


def copy_regular(source, destination):
    if source.is_symlink():
        raise ValueError(f'framework sources cannot be symlinks: {source}')
    if source.is_dir():
        destination.mkdir(parents=True, exist_ok=True)
        for child in sorted(source.iterdir()):
            if child.name != '__pycache__' and child.suffix != '.pyc':
                copy_regular(child, destination / child.name)
    elif source.is_file():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
        destination.chmod(0o755 if source.stat().st_mode & 0o111 else 0o644)
    else:
        raise ValueError(f'framework source is not a regular file: {source}')


def local_source(reference):
    value = reference.removeprefix('path:')
    if reference.startswith('path:') or Path(value).exists():
        return resolve_root(value)
    return None


@contextmanager
def framework_source(reference):
    local = local_source(str(reference))
    with tempfile.TemporaryDirectory(prefix='nixodoo-framework-') as temporary:
        if local:
            snapshot = resolve_root(temporary) / 'framework'
            snapshot.mkdir()
            # Do not pass project runtime files or credentials to the Nix store.
            for name in ('flake.nix', 'flake.lock', 'nix'):
                copy_regular(local / name, snapshot / name)
            metadata = json.loads(run(['nix', 'flake', 'metadata', '--json', '--no-write-lock-file', 'path:' + str(snapshot)]))
        else:
            metadata = json.loads(run(['nix', 'flake', 'metadata', '--json', '--no-write-lock-file', '--refresh', reference]))
        locked = metadata['locked']
        provenance = {'kind': 'local', 'narHash': locked['narHash']}
        if not local and locked.get('rev'):
            provenance = {'kind': 'git', 'source': str(reference), 'revision': locked['rev'], 'narHash': locked['narHash']}
        yield resolve_root(metadata['path']), provenance


def nix_arguments(framework, config, provenance, system, target):
    return ['--impure', '--file', framework / 'nix/generator/prepare.nix',
            '--argstr', 'frameworkRoot', framework, '--argstr', 'configFile', config,
            '--argstr', 'provenanceJson', json.dumps(provenance), '--argstr', 'system', system,
            '--argstr', 'target', target]


def build(framework, config, provenance, system, target='candidate'):
    result = run(['nix', 'build', '--no-link', '--json', *nix_arguments(framework, config, provenance, system, target)])
    return resolve_root(json.loads(result)[0]['outputs']['out'])


def evaluate_config(framework, config, system):
    try:
        arguments = nix_arguments(framework, config, {}, system, 'config')
        arguments.remove('--file')
        return json.loads(run(['nix-instantiate', '--eval', '--strict', '--json', *arguments]))
    except CommandError as error:
        raise CommandError(f'configuration must be valid and self-contained:\n{error}') from error


def mutable_candidate(source, destination):
    copy_regular(source, destination)
    manifest = read_json(destination / 'manifest.json')
    for path, declaration in manifest['files'].items():
        (destination / 'tree' / path).chmod(declaration['mode'])
    return manifest


def add_seed(candidate, manifest, name, data):
    path = candidate / 'tree' / name
    path.write_bytes(data)
    path.chmod(0o644)
    manifest['files'][name] = {'sha256': hashlib.sha256(data).hexdigest(), 'mode': 0o644, 'ownership': 'seed'}
    (candidate / 'manifest.json').write_text(json.dumps(manifest, indent=2, sort_keys=True) + '\n')


def lock_dependencies(directory, tools, *, requirements=None):
    arguments = [tools / 'bin/uv']
    if requirements:
        run([*arguments, 'add', '--no-sync', '--no-python-downloads', '--python', tools / 'bin/python',
             '-r', requirements], cwd=directory)
    run([*arguments, 'lock', '--no-python-downloads', '--python', tools / 'bin/python'], cwd=directory)


def init_project(arguments, framework_reference, system):
    display_destination = arguments.destination.absolute()
    destination = checked_path(resolve_root(display_destination.parent), display_destination.name)
    if destination.exists() and (not destination.is_dir() or any(destination.iterdir())):
        raise ValueError(f'initialization requires a new or empty directory: {destination}')
    if not destination.parent.is_dir():
        raise ValueError(f'parent directory does not exist: {destination.parent}')
    with tempfile.TemporaryDirectory(prefix='.nixodoo-init-', dir=destination.parent) as temporary:
        temporary = resolve_root(temporary)
        config = temporary / 'config.nix'
        if arguments.config:
            if arguments.project_name or arguments.odoo:
                raise ValueError('use --config or the project flags, not both')
            copy_regular(arguments.config.absolute(), config)
        else:
            if not arguments.project_name:
                raise ValueError('init requires --config or --project-name')
            config.write_text(nix_value({'projectName': arguments.project_name,
                                         **({'odooVersion': arguments.odoo} if arguments.odoo else {})}) + '\n')
        with framework_source(framework_reference) as (framework, provenance):
            if os.environ.get('NIXODOO_PROVENANCE'):
                provenance = json.loads(os.environ['NIXODOO_PROVENANCE'])
            evaluate_config(framework, config, system)
            candidate = temporary / 'candidate'
            manifest = mutable_candidate(build(framework, config, provenance, system), candidate)
            tools = build(framework, config, provenance, system, 'tools')
            lock_dependencies(candidate / 'tree', tools)
            add_seed(candidate, manifest, 'uv.lock', (candidate / 'tree/uv.lock').read_bytes())
            stage = temporary / 'project'
            stage.mkdir()
            apply_resolved_update(stage, candidate)
            run(['git', 'init', '--initial-branch=main', stage])
            run(['git', 'add', '--all'], cwd=stage)
            # Check again after preparation, before replacing an empty destination.
            checked_path(destination.parent, destination.name)
            if destination.exists():
                if any(destination.iterdir()):
                    raise ConflictError([str(destination)], 'initialization target became nonempty')
                destination.rmdir()
            os.rename(stage, destination)
    print(f'Created {display_destination}')
    return 0


def metadata_edit(name, data, state):
    return FileEdit(name, data, state['sha256'] if state else None, state['mode'] if state else None,
                    canonical_mode(state['mode']) if state else 0o644)


def report_runtime(previous, current):
    if previous.get('postgres') != current['postgres']:
        print('PostgreSQL version changed: migrate the database explicitly before starting the new server.')
    if any(previous.get(key) != current.get(key) for key in
           ('ports', 'dbName', 'dbUser', 'dbPasswordFile', 'serviceSuffix', 'odooVersion')):
        print('Runtime configuration changed: review .env, odoo.conf, nginx, and user units, then refresh them explicitly.')


def report_preserved(project, candidate, manifest, operations):
    changing = {operation.path for operation in operations}
    desired = read_json(candidate / 'manifest.json')['files']
    for name, declaration in sorted(manifest['files'].items()):
        if declaration['ownership'] != 'seed' or name in changing:
            continue
        try:
            actual = read_state(project, name)
        except ConflictError:
            actual = None
        expected = desired.get(name, declaration)
        if not matches(actual, expected):
            print(f'preserved: {name} (project-owned file differs or is missing)')


def refresh_project(arguments, framework_reference, system):
    project = resolve_root(Path.cwd())
    installed = load_manifest(project, MANIFEST)
    config_file = checked_path(project, 'config.nix')
    if read_state(project, 'config.nix') is None:
        raise ValueError('missing project config.nix')
    states = {name: read_state(project, name) for name in ('config.nix', 'pyproject.toml', 'uv.lock')}
    originals = {name: (project / name).read_bytes() if state else None for name, state in states.items()}
    if originals['pyproject.toml'] is None:
        raise ValueError('missing pyproject.toml')
    with tempfile.TemporaryDirectory(prefix='nixodoo-refresh-') as temporary:
        temporary = resolve_root(temporary)
        config = temporary / 'config.nix'
        config.write_bytes(originals['config.nix'])
        # Refresh uses only the project's vendored implementation and lock file.
        reference = project
        if arguments.command == 'update':
            reference = arguments.source
            if not reference:
                with framework_source(project) as (vendored, _):
                    reference = evaluate_config(vendored, config, system)['frameworkSource']
        with framework_source(reference) as (framework, provenance):
            if arguments.command != 'update':
                provenance = installed['provenance']
            current_config = evaluate_config(framework, config, system)
            candidate = build(framework, config, provenance, system)
            expected = candidate / 'tree/pyproject.toml'
            proposed = plan_metadata(originals['pyproject.toml'].decode(), expected.read_text(),
                                     previous_overrides=installed.get('pythonOverrides', []))
            before = tomllib.loads(originals['pyproject.toml'].decode())
            after = tomllib.loads(proposed)
            dependencies_changed = any(before['project'].get(key) != after['project'].get(key)
                                       for key in ('requires-python', 'dependencies'))
            dependencies_changed |= (before.get('tool', {}).get('uv', {}).get('override-dependencies', [])
                                     != after.get('tool', {}).get('uv', {}).get('override-dependencies', []))
            edits = [metadata_edit('pyproject.toml', proposed.encode(), states['pyproject.toml'])]
            if arguments.command == 'refresh-deps':
                workspace = temporary / 'dependencies'
                workspace.mkdir()
                (workspace / 'pyproject.toml').write_text(proposed)
                if originals['uv.lock'] is not None:
                    (workspace / 'uv.lock').write_bytes(originals['uv.lock'])
                requirements = checked_path(project, 'src/odoo/requirements.txt')
                if requirements.exists() and read_state(project, 'src/odoo/requirements.txt') is None:
                    raise ValueError('requirements.txt must be a regular file')
                tools = build(framework, config, provenance, system, 'tools')
                lock_dependencies(workspace, tools, requirements=requirements if requirements.exists() else None)
                edits = [metadata_edit(name, (workspace / name).read_bytes(), states[name])
                         for name in ('pyproject.toml', 'uv.lock')]
            edits.append(metadata_edit('config.nix', originals['config.nix'], states['config.nix']))
            operations, resulting_manifest = prepare_resolved_update(project, candidate, edits=edits)
            report_preserved(project, candidate, resulting_manifest, operations)
            changed = bool(operations) or installed != resulting_manifest
            for operation in operations:
                print(f'{operation.action}: {operation.path}')
            if changed and not operations:
                print('update: .nixodoo/manifest.json')
            report_runtime(installed['config'], current_config)
            if dependencies_changed and arguments.command != 'refresh-deps':
                print('Python dependency metadata changed: run nix run .#refresh-deps to update uv.lock.')
            if arguments.check:
                return 1 if changed else 0
            apply_resolved_update(project, candidate, edits=edits)
    print('Project metadata refreshed.' if changed else 'Project is up to date.')
    return 0


def parser():
    result = argparse.ArgumentParser(description=__doc__)
    commands = result.add_subparsers(dest='command', required=True)
    init = commands.add_parser('init', help='create a project with a bootstrapped dependency lock')
    init.add_argument('destination', type=Path)
    init.add_argument('--config', type=Path)
    init.add_argument('--project-name')
    init.add_argument('--odoo', choices=['17.0', '18.0', '19.0'])
    for name in ('update', 'refresh-config', 'refresh-deps'):
        command = commands.add_parser(name)
        command.add_argument('--check', action='store_true')
        if name == 'update':
            command.add_argument('--from', dest='source')
    commands.add_parser('recover', help='restore files from an interrupted update')
    return result


def main(argv=None):
    arguments = parser().parse_args(argv)
    framework = os.environ.get('NIXODOO_FRAMEWORK_ROOT', str(Path(__file__).resolve().parents[2]))
    system = os.environ.get('NIXODOO_SYSTEM')
    try:
        if not system:
            raise ValueError('NIXODOO_SYSTEM must be supplied by the pinned Nix app')
        if arguments.command == 'init':
            return init_project(arguments, framework, system)
        if arguments.command == 'recover':
            recover(Path.cwd())
            print('Recovery complete.')
            return 0
        return refresh_project(arguments, framework, system)
    except (OSError, ValueError, ConflictError) as error:
        print(f'error: {error}', file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main())
