"""Create, update, refresh, and recover projects generated by Nix."""

import argparse
from contextlib import contextmanager
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import tomllib

from dependencies import plan_metadata
from transaction import (ConflictError, FileEdit, MANIFEST, apply_update, checked_path,
                         canonical_mode, load_manifest, matches, prepare_update, read_json,
                         read_state, recover, validate_path, RESERVED)


class CommandError(ValueError):
    pass


def run(arguments, *, cwd=None):
    result = subprocess.run(list(map(str, arguments)), cwd=cwd, capture_output=True, text=True)
    if result.returncode:
        raise CommandError(f'{arguments[0]} failed:\n{result.stderr.strip()}')
    return result.stdout


def nix_value(value):
    """Serialize explicit CLI values without evaluating them as Nix source."""
    if isinstance(value, str):
        if any(ord(char) < 32 and char not in '\n\r\t' for char in value):
            raise ValueError('configuration strings contain unsupported control characters')
        return json.dumps(value, ensure_ascii=False).replace('${', '\\${')
    if value is None:
        return 'null'
    if type(value) is bool:
        return 'true' if value else 'false'
    if type(value) is int:
        return str(value)
    if type(value) is float:
        return '(builtins.fromJSON ' + nix_value(json.dumps(value, allow_nan=False)) + ')'
    if isinstance(value, list):
        return '[ ' + ' '.join(nix_value(item) for item in value) + ' ]'
    if isinstance(value, dict):
        return '{ ' + ' '.join(f'{nix_value(key)} = {nix_value(item)};' for key, item in value.items()) + ' }'
    raise ValueError(f'unsupported configuration value: {type(value).__name__}')


def copy_regular(source, destination):
    if source.is_symlink():
        raise ValueError(f'framework sources cannot be symlinks: {source}')
    if source.is_dir():
        destination.mkdir(parents=True, exist_ok=True)
        for child in sorted(source.iterdir()):
            if child.name != '__pycache__' and child.suffix != '.pyc':
                copy_regular(child, destination / child.name)
    elif source.is_file():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
        destination.chmod(0o755 if source.stat().st_mode & 0o111 else 0o644)
    else:
        raise ValueError(f'framework source is not a regular file: {source}')


def local_source(reference):
    value = reference.removeprefix('path:')
    if reference.startswith('path:') or Path(value).exists():
        return Path(value).absolute()
    return None


@contextmanager
def framework_source(reference):
    local = local_source(str(reference))
    with tempfile.TemporaryDirectory(prefix='nixodoo-framework-') as temporary:
        if local:
            snapshot = Path(temporary) / 'framework'
            snapshot.mkdir()
            # Do not pass project runtime files or credentials to the Nix store.
            for name in ('flake.nix', 'flake.lock', 'nix'):
                copy_regular(local / name, snapshot / name)
            metadata = json.loads(run(['nix', 'flake', 'metadata', '--json', '--no-write-lock-file', 'path:' + str(snapshot)]))
        else:
            metadata = json.loads(run(['nix', 'flake', 'metadata', '--json', '--no-write-lock-file', '--refresh', reference]))
        locked = metadata['locked']
        provenance = {'kind': 'local', 'narHash': locked['narHash']}
        if not local and locked.get('rev'):
            provenance = {'kind': 'git', 'source': str(reference), 'revision': locked['rev'], 'narHash': locked['narHash']}
        yield Path(metadata['path']), provenance


def nix_arguments(framework, config, provenance, system, target):
    return ['--impure', '--file', framework / 'nix/generator/prepare.nix',
            '--argstr', 'frameworkRoot', framework, '--argstr', 'configFile', config,
            '--argstr', 'provenanceJson', json.dumps(provenance), '--argstr', 'system', system,
            '--argstr', 'target', target]


def build(framework, config, provenance, system, target='candidate'):
    result = run(['nix', 'build', '--no-link', '--json', *nix_arguments(framework, config, provenance, system, target)])
    return Path(json.loads(result)[0]['outputs']['out'])


def evaluate_config(framework, config, system):
    try:
        arguments = nix_arguments(framework, config, {}, system, 'config')
        arguments.remove('--file')
        return json.loads(run(['nix-instantiate', '--eval', '--strict', '--json', *arguments]))
    except CommandError as error:
        raise CommandError(f'configuration must be valid and self-contained:\n{error}') from error


def mutable_candidate(source, destination):
    copy_regular(source, destination)
    manifest = read_json(destination / 'manifest.json')
    for path, declaration in manifest['files'].items():
        (destination / 'tree' / path).chmod(declaration['mode'])
    return manifest


def add_seed(candidate, manifest, name, data):
    path = candidate / 'tree' / name
    path.write_bytes(data)
    path.chmod(0o644)
    manifest['files'][name] = {'sha256': hashlib.sha256(data).hexdigest(), 'mode': 0o644, 'ownership': 'seed'}
    (candidate / 'manifest.json').write_text(json.dumps(manifest, indent=2, sort_keys=True) + '\n')


def lock_dependencies(directory, tools, *, requirements=None):
    arguments = [tools / 'bin/uv']
    if requirements:
        run([*arguments, 'add', '--no-sync', '--no-python-downloads', '--python', tools / 'bin/python',
             '-r', requirements], cwd=directory)
    run([*arguments, 'lock', '--no-python-downloads', '--python', tools / 'bin/python'], cwd=directory)


def init_project(arguments, framework_reference, system):
    destination = arguments.destination.absolute()
    checked_path(destination.parent, destination.name)
    if destination.exists() and (not destination.is_dir() or any(destination.iterdir())):
        raise ValueError(f'initialization requires a new or empty directory: {destination}')
    if not destination.parent.is_dir():
        raise ValueError(f'parent directory does not exist: {destination.parent}')
    with tempfile.TemporaryDirectory(prefix='.nixodoo-init-', dir=destination.parent) as temporary:
        temporary = Path(temporary)
        config = temporary / 'config.nix'
        if arguments.config:
            if arguments.project_name or arguments.odoo:
                raise ValueError('use --config or the project flags, not both')
            copy_regular(arguments.config.absolute(), config)
        else:
            if not arguments.project_name:
                raise ValueError('init requires --config or --project-name')
            config.write_text(nix_value({'projectName': arguments.project_name,
                                         **({'odooVersion': arguments.odoo} if arguments.odoo else {})}) + '\n')
        with framework_source(framework_reference) as (framework, provenance):
            if os.environ.get('NIXODOO_PROVENANCE'):
                provenance = json.loads(os.environ['NIXODOO_PROVENANCE'])
            evaluate_config(framework, config, system)
            candidate = temporary / 'candidate'
            manifest = mutable_candidate(build(framework, config, provenance, system), candidate)
            tools = build(framework, config, provenance, system, 'tools')
            lock_dependencies(candidate / 'tree', tools)
            add_seed(candidate, manifest, 'uv.lock', (candidate / 'tree/uv.lock').read_bytes())
            stage = temporary / 'project'
            stage.mkdir()
            apply_update(stage, candidate)
            run(['git', 'init', '--initial-branch=main', stage])
            run(['git', 'add', '--all'], cwd=stage)
            # Check again after preparation, before replacing an empty destination.
            checked_path(destination.parent, destination.name)
            if destination.exists():
                if any(destination.iterdir()):
                    raise ConflictError([str(destination)], 'initialization target became nonempty')
                destination.rmdir()
            os.rename(stage, destination)
    print(f'Created {destination}')
    return 0


def metadata_edit(name, data, state):
    return FileEdit(name, data, state['sha256'] if state else None, state['mode'] if state else None,
                    canonical_mode(state['mode']) if state else 0o644)


def report_runtime(previous, current):
    if previous.get('postgres') != current['postgres']:
        print('PostgreSQL version changed: migrate the database explicitly before starting the new server.')
    if any(previous.get(key) != current.get(key) for key in
           ('ports', 'dbName', 'dbUser', 'dbPasswordFile', 'serviceSuffix', 'odooVersion')):
        print('Runtime configuration changed: review .env, odoo.conf, nginx, and user units, then refresh them explicitly.')


def report_preserved(project, candidate, manifest, operations):
    changing = {operation.path for operation in operations}
    desired = read_json(candidate / 'manifest.json')['files']
    for name, declaration in sorted(manifest['files'].items()):
        if declaration['ownership'] != 'seed' or name in changing:
            continue
        try:
            actual = read_state(project, name)
        except ConflictError:
            actual = None
        expected = desired.get(name, declaration)
        if not matches(actual, expected):
            print(f'preserved: {name} (project-owned file differs or is missing)')


def refresh_project(arguments, framework_reference, system):
    project = Path.cwd()
    installed = load_manifest(project, MANIFEST)
    config_file = checked_path(project, 'config.nix')
    if read_state(project, 'config.nix') is None:
        raise ValueError('missing project config.nix')
    states = {name: read_state(project, name) for name in ('config.nix', 'pyproject.toml', 'uv.lock')}
    originals = {name: (project / name).read_bytes() if state else None for name, state in states.items()}
    if originals['pyproject.toml'] is None:
        raise ValueError('missing pyproject.toml')
    with tempfile.TemporaryDirectory(prefix='nixodoo-refresh-') as temporary:
        temporary = Path(temporary)
        config = temporary / 'config.nix'
        config.write_bytes(originals['config.nix'])
        # Refresh uses only the project's vendored implementation and lock file.
        reference = project
        if arguments.command == 'update':
            reference = arguments.source
            if not reference:
                with framework_source(project) as (vendored, _):
                    reference = evaluate_config(vendored, config, system)['frameworkSource']
        with framework_source(reference) as (framework, provenance):
            if arguments.command != 'update':
                provenance = installed['provenance']
            current_config = evaluate_config(framework, config, system)
            candidate = build(framework, config, provenance, system)
            expected = candidate / 'tree/pyproject.toml'
            proposed = plan_metadata(originals['pyproject.toml'].decode(), expected.read_text(),
                                     previous_overrides=installed.get('pythonOverrides', []))
            before = tomllib.loads(originals['pyproject.toml'].decode())
            after = tomllib.loads(proposed)
            dependencies_changed = any(before['project'].get(key) != after['project'].get(key)
                                       for key in ('requires-python', 'dependencies'))
            dependencies_changed |= (before.get('tool', {}).get('uv', {}).get('override-dependencies', [])
                                     != after.get('tool', {}).get('uv', {}).get('override-dependencies', []))
            edits = [metadata_edit('pyproject.toml', proposed.encode(), states['pyproject.toml'])]
            if arguments.command == 'refresh-deps':
                workspace = temporary / 'dependencies'
                workspace.mkdir()
                (workspace / 'pyproject.toml').write_text(proposed)
                if originals['uv.lock'] is not None:
                    (workspace / 'uv.lock').write_bytes(originals['uv.lock'])
                requirements = checked_path(project, 'src/odoo/requirements.txt')
                if requirements.exists() and read_state(project, 'src/odoo/requirements.txt') is None:
                    raise ValueError('requirements.txt must be a regular file')
                tools = build(framework, config, provenance, system, 'tools')
                lock_dependencies(workspace, tools, requirements=requirements if requirements.exists() else None)
                edits = [metadata_edit(name, (workspace / name).read_bytes(), states[name])
                         for name in ('pyproject.toml', 'uv.lock')]
            edits.append(metadata_edit('config.nix', originals['config.nix'], states['config.nix']))
            operations, resulting_manifest = prepare_update(project, candidate, edits=edits)
            report_preserved(project, candidate, resulting_manifest, operations)
            changed = bool(operations) or installed != resulting_manifest
            for operation in operations:
                print(f'{operation.action}: {operation.path}')
            if changed and not operations:
                print('update: .nixodoo/manifest.json')
            report_runtime(installed['config'], current_config)
            if dependencies_changed and arguments.command != 'refresh-deps':
                print('Python dependency metadata changed: run nix run .#refresh-deps to update uv.lock.')
            if arguments.check:
                return 1 if changed else 0
            apply_update(project, candidate, edits=edits)
    print('Project metadata refreshed.' if changed else 'Project is up to date.')
    return 0


def migrate_project(arguments, framework_reference, system):
    from migrate import SECRET_PATH, import_answers, import_customizations, parse_yaml, validate_preserve

    project = arguments.project.absolute()
    if Path(run(['git', '-C', project, 'rev-parse', '--show-toplevel']).strip()).resolve() != project.resolve():
        raise ValueError('migration requires a Git repository rooted at the project directory')
    if read_state(project, MANIFEST) is not None:
        raise ValueError('project already has a generator manifest; use update or refresh-config')
    tracked = set(run(['git', 'ls-files', '-z'], cwd=project).split('\0'))
    private_tracked = [name for name in tracked if any(name == root or name.startswith(root + '/') for root in RESERVED)]
    if private_tracked:
        raise ConflictError(private_tracked, 'runtime files are tracked by Git; untrack them before migration')
    answers = validate_path(arguments.answers or '.copier-answers.yml')
    answer_state, config_state = read_state(project, answers), read_state(project, 'config.nix')
    if answer_state and config_state and not arguments.answers:
        raise ValueError('both legacy answers and config.nix exist; select the answers explicitly with --answers')
    originals = {}
    for name, state in ((answers, answer_state), ('config.nix', config_state)):
        if state:
            originals[name] = ((project / name).read_bytes(), state)
    if answer_state:
        values = parse_yaml(originals[answers][0].decode())
    elif config_state:
        try:
            values = json.loads(run(['nix-instantiate', '--eval', '--strict', '--json',
                                     Path(__file__).parent / 'legacy-config.nix',
                                     '--argstr', 'configFile', project / 'config.nix']))
        except CommandError as error:
            raise ValueError('cannot evaluate legacy config.nix; review its syntax and imports') from error
    else:
        raise ValueError('no legacy answers or config.nix found')
    settings, secret = import_answers(values)
    settings, imported = import_customizations(project, settings)
    preserved = {validate_preserve(path) for path in arguments.preserve}
    if preserved & {answers, 'config.nix'}:
        raise ValueError('legacy settings must be converted and backed up, not preserved in the active project')
    managed = set(arguments.manage)
    if managed - imported.keys() or managed & preserved:
        raise ValueError('--manage must select imported settings files that are not also preserved')
    if secret:
        for name in ('CLAUDE.md', '.claude/project-context.md'):
            if read_state(project, name) and secret.rstrip(b'\n') in (project / name).read_bytes():
                raise ConflictError([name], 'remove the legacy credential from project instructions before migration')
    with tempfile.TemporaryDirectory(prefix='nixodoo-migrate-') as temporary:
        temporary = Path(temporary)
        config = temporary / 'config.nix'
        config.write_text(nix_value(settings) + '\n')
        with framework_source(framework_reference) as (framework, provenance):
            if os.environ.get('NIXODOO_PROVENANCE'):
                provenance = json.loads(os.environ['NIXODOO_PROVENANCE'])
            evaluate_config(framework, config, system)
            candidate = build(framework, config, provenance, system)
            desired = read_json(candidate / 'manifest.json')
            adoption = dict(desired, files={}, ownershipOverrides={})
            edits = []

            def adopt(name, state, owner='managed'):
                if state:
                    adoption['files'][name] = dict(state, mode=canonical_mode(state['mode']), ownership=owner)
                if owner == 'seed':
                    adoption['ownershipOverrides'][name] = 'seed'

            def private_write(name, data):
                state = read_state(project, name)
                if state:
                    if (project / name).read_bytes() != data:
                        raise ConflictError([name], 'existing migration backup differs; review and move that backup aside before retrying')
                    if state['mode'] == 0o600:
                        return
                edits.append(FileEdit(name, data, state['sha256'] if state else None,
                                      state['mode'] if state else None, mode=0o600, private=True))

            for name, (data, state) in originals.items():
                adopt(name, state, 'seed' if name == 'config.nix' else 'managed')
                private_write('.nixodoo/migration-backup/' + name, data)
            edits.append(metadata_edit('config.nix', config.read_bytes(), config_state))
            if secret:
                existing = read_state(project, SECRET_PATH)
                private_write(SECRET_PATH, (project / SECRET_PATH).read_bytes() if existing else secret)
            for name, state in imported.items():
                if name not in desired['files']:
                    raise ConflictError([name], 'imported customization is disabled by the selected project options')
                adopt(name, state, 'managed' if name in managed else 'seed')
            for name in preserved:
                adopt(name, read_state(project, name), 'seed')
            ignore_state = read_state(project, '.gitignore')
            ignore = (project / '.gitignore').read_bytes() if ignore_state else b''
            required_ignore = (candidate / 'tree/.gitignore').read_bytes()
            merged_ignore = ignore.rstrip(b'\n') + b'\n' + required_ignore
            adopt('.gitignore', ignore_state, 'seed')
            edits.append(metadata_edit('.gitignore', merged_ignore, ignore_state))
            if arguments.baseline:
                baseline = arguments.baseline.absolute()
                for path in baseline.rglob('*'):
                    name = path.relative_to(baseline).as_posix()
                    if not path.is_file() and not path.is_symlink():
                        continue
                    try:
                        validate_path(name)
                    except ValueError:
                        continue
                    declaration = desired['files'].get(name, {})
                    is_code = name.startswith('nix/') or name in ('flake.nix', 'flake.lock')
                    is_claude = name.startswith('.claude/') and not name.startswith('.claude/memory-template/')
                    if (name in adoption['files'] or declaration.get('ownership') == 'seed'
                            or not (is_code or is_claude)):
                        continue
                    state = read_state(project, name)
                    baseline_state = read_state(baseline, name)
                    if baseline_state is not None and matches(
                            state, dict(baseline_state, mode=canonical_mode(baseline_state['mode']))):
                        adopt(name, state)
            unknown = []
            for path in (project / 'nix').rglob('*'):
                name = path.relative_to(project).as_posix()
                if (path.is_dir() and not path.is_symlink()) or '__pycache__' in path.parts or path.suffix == '.pyc':
                    continue
                if name not in desired['files'] and name not in adoption['files']:
                    unknown.append(name)
            if unknown:
                raise ConflictError(unknown, 'unrecognized framework files require review')
            metadata_state = read_state(project, 'pyproject.toml')
            generated_metadata = (candidate / 'tree/pyproject.toml').read_text()
            metadata = (project / 'pyproject.toml').read_text() if metadata_state else generated_metadata
            proposed = plan_metadata(metadata, generated_metadata)
            lock_state = read_state(project, 'uv.lock')
            if lock_state is None:
                workspace = temporary / 'dependencies'
                workspace.mkdir()
                (workspace / 'pyproject.toml').write_text(proposed)
                tools = build(framework, config, provenance, system, 'tools')
                lock_dependencies(workspace, tools)
                edits.append(metadata_edit('uv.lock', (workspace / 'uv.lock').read_bytes(), None))
            edits.append(metadata_edit('pyproject.toml', proposed.encode(), metadata_state))
            operations, result_manifest = prepare_update(project, candidate, adoption=adoption, edits=edits)
            report_preserved(project, candidate, result_manifest, operations)
            print(f'Candidate for review: {candidate}/tree')
            for operation in operations:
                print(f'{operation.action}: {operation.path}')
            if arguments.check:
                return 1
            apply_update(project, candidate, adoption=adoption, edits=edits)
            tracked = set(run(['git', 'ls-files', '-z'], cwd=project).split('\0'))
            changed = [operation.path for operation in operations
                       if not operation.path.startswith(('.nixodoo/secrets/', '.nixodoo/migration-backup/'))
                       and (operation.action != 'delete' or operation.path in tracked)]
            changed = sorted(set(changed) | {name for name in result_manifest['files'] if (project / name).is_file()})
            run(['git', 'add', '-f', '-A', '--', *changed, MANIFEST], cwd=project)
    print('Migration complete. Review the staged files before committing.')
    return 0


def parser():
    result = argparse.ArgumentParser(description=__doc__)
    commands = result.add_subparsers(dest='command', required=True)
    init = commands.add_parser('init', help='create a project with a bootstrapped dependency lock')
    init.add_argument('destination', type=Path)
    init.add_argument('--config', type=Path)
    init.add_argument('--project-name')
    init.add_argument('--odoo', choices=['17.0', '18.0', '19.0'])
    for name in ('update', 'refresh-config', 'refresh-deps'):
        command = commands.add_parser(name)
        command.add_argument('--check', action='store_true')
        if name == 'update':
            command.add_argument('--from', dest='source')
    commands.add_parser('recover', help='restore files from an interrupted update')
    migration = commands.add_parser('migrate', help='import a legacy project with explicit file ownership')
    migration.add_argument('project', type=Path)
    migration.add_argument('--check', action='store_true')
    migration.add_argument('--answers', help='relative path to the legacy YAML answers')
    migration.add_argument('--preserve', action='append', default=[], metavar='PATH')
    migration.add_argument('--manage', action='append', default=[], metavar='PATH',
                           help='replace an imported settings file with its Nix-generated form')
    migration.add_argument('--baseline', type=Path, help='pristine legacy project used to verify unchanged framework files')
    return result


def main(argv=None):
    arguments = parser().parse_args(argv)
    framework = os.environ.get('NIXODOO_FRAMEWORK_ROOT', str(Path(__file__).resolve().parents[2]))
    system = os.environ.get('NIXODOO_SYSTEM')
    try:
        if not system:
            raise ValueError('NIXODOO_SYSTEM must be supplied by the pinned Nix app')
        if arguments.command == 'init':
            return init_project(arguments, framework, system)
        if arguments.command == 'recover':
            recover(Path.cwd())
            print('Recovery complete.')
            return 0
        if arguments.command == 'migrate':
            return migrate_project(arguments, framework, system)
        return refresh_project(arguments, framework, system)
    except (OSError, ValueError, ConflictError) as error:
        print(f'error: {error}', file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main())
